name:                draughts-online
version:             0.1.0.0
github:              "githubuser/draughts-online"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/draughts-online#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- Spock
- Spock-core
- http-types
- text
- aeson
- unordered-containers
- vector
- colour
- brick
- vty
- wreq
- lens
- http-client
- utf8-string
- QuickCheck


library:
  source-dirs: src

executables:
  draughts-online-client-exe:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - draughts-online
  
  draughts-online-host-exe:
    main:                Main.hs
    source-dirs:         host
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - draughts-online

tests:
  draughts-online-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - draughts-online

